import os

SLACK_TOKEN=os.environ["SLACK_TOKEN"]
SLACK_SIGNING_SECRET=os.environ["SLACK_SIGNING_SECRET"]
SLACK_CHANNEL_LOG=os.environ["SLACK_CHANNEL_LOG"]
AWS_NORMAL_ACCESS_KEY_ID=os.environ["AWS_NORMAL_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY_ID=os.environ["AWS_SECRET_ACCESS_KEY_ID"]
AWS_S3_BUCKET_NAME=os.environ["AWS_S3_BUCKET_NAME"]
AWS_S3_URL=os.environ["AWS_S3_URL"]